name: YAPF Formatting
on:
  push:
    branches: [ feature/vote-on-proposals ]
  pull_request:
    branches: [ master ]
jobs:
  formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run YAPF to format python code
      uses: block42-blockchain-company/yapf-action@master
      with:
        args: "--verbose --style='{based_on_style: pep8; COLUMN_LIMIT: 119}'"
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Commit formatted code
      with:
        commit_message: YAPF format
        commit_user_name: block42-laborer
        commit_user_email: admin@block42.tech

